server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/organizodb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: seu_usuario
    password: sua_senha
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      show-sql: false
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: seu_usuario
    password: sua_senha
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: 2iBecb8ediK1vGpxBSy7/+uryEa8+aDB5DHVOWWhF0zaRDngFY8aPe3mIIuuMCdnKXmHDuSvKnvpwYwc5KdwoQ==
          expiration: 360000

jwt:
  secret: 2iBecb8ediK1vGpxBSy7/+uryEa8+aDB5DHVOWWhF0zaRDngFY8aPe3mIIuuMCdnKXmHDuSvKnvpwYwc5KdwoQ==
  expiration: 360000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
  api-docs:
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always